default:
  image: habit-lens-runtime-alpine

stages:
  - test


test:backend:
  variables:
    MAVEN_USER_HOME: "$CI_PROJECT_DIR/.m2"
  cache:
    key: maven
    paths:
      - .m2/repository
  script:
    - cd backend
    - ./mvnw test

pages:
  script:
    - cd client
    - export VITE_BASE_PATH="/habit-lens/"
    - bun install
    - bun vite build
    - mv dist ../public
  artifacts:
    paths:
      - public
