#default:

#stages:
#  -

test:backend:
  image: vegardit/graalvm-maven:latest-java25
  variables:
    MAVEN_USER_HOME: "$CI_PROJECT_DIR/.m2"
  cache:
    key: maven
    paths:
      - .m2/repository
  script:
    - cd backend
    - ./mvnw test

deploy:client:
  image: node:lts
  cache:
    key: node
    paths:
      - client/node_modules
  script:
    - cd client
    - curl -fsSL https://bun.sh/install | bash
    - export PATH="$HOME/.bun/bin:$PATH"
    - bun i
    - bun vite build
    - bun vite preview