#default:

#stages:
#  -

test:backend:
  image: vegardit/graalvm-maven:latest-java25
  variables:
    MAVEN_USER_HOME: "$CI_PROJECT_DIR/.m2"
  cache:
    key: maven
    paths:
      - .m2/repository
  script:
    - cd backend
    - ./mvnw test

deploy:client:
  image: node:lts
  cache:
    key: node
    paths:
      - frontend/node_modules
  script:
    - cd client
    - bun i
    - bun vite build